model_name: "LateFusion"

# image_model: "Vgg"
image_model: "Resnet"

text_model: "Lstm"
# text_model: "GRU"

option: "mean"

data_mode: "basic"
image_type: "raw"
text_type: "token"
task: "fusion"
select_metric: "loss"

num_epochs: 10
learning_rate: 0.0001
batch_size: 64
val_epoch: 1
finetune: False

word_dim: 200            # dim of word
hidden_dim: 128           # dim of modal
num_labels: 80            # num of labels